<?php

/**
 * BaseDistrict
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $name_ar
 * @property integer $city_id
 * @property City $City
 * 
 * @method integer  getId()      Returns the current record's "id" value
 * @method string   getName()    Returns the current record's "name" value
 * @method string   getNameAr()  Returns the current record's "name_ar" value
 * @method integer  getCityId()  Returns the current record's "city_id" value
 * @method City     getCity()    Returns the current record's "City" value
 * @method District setId()      Sets the current record's "id" value
 * @method District setName()    Sets the current record's "name" value
 * @method District setNameAr()  Sets the current record's "name_ar" value
 * @method District setCityId()  Sets the current record's "city_id" value
 * @method District setCity()    Sets the current record's "City" value
 * 
 * @package    realstate
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDistrict extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('district');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name_ar', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('city_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('City', array(
             'local' => 'city_id',
             'foreign' => 'id'));
    }
}