<?php

/**
 * BaseCurrency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $name_ar
 * @property string $code
 * @property string $code_ar
 * @property string $symbol
 * @property Doctrine_Collection $State
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method string              getNameAr()  Returns the current record's "name_ar" value
 * @method string              getCode()    Returns the current record's "code" value
 * @method string              getCodeAr()  Returns the current record's "code_ar" value
 * @method string              getSymbol()  Returns the current record's "symbol" value
 * @method Doctrine_Collection getState()   Returns the current record's "State" collection
 * @method Currency            setId()      Sets the current record's "id" value
 * @method Currency            setName()    Sets the current record's "name" value
 * @method Currency            setNameAr()  Sets the current record's "name_ar" value
 * @method Currency            setCode()    Sets the current record's "code" value
 * @method Currency            setCodeAr()  Sets the current record's "code_ar" value
 * @method Currency            setSymbol()  Sets the current record's "symbol" value
 * @method Currency            setState()   Sets the current record's "State" collection
 * 
 * @package    realstate
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCurrency extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('currency');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('name_ar', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('code', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('code_ar', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('symbol', 'string', 3, array(
             'type' => 'string',
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('State', array(
             'local' => 'id',
             'foreign' => 'currency_id'));
    }
}