<?php

/**
 * BaseNewsletters
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $email
 * @property boolean $subscribe
 * 
 * @method integer     getId()        Returns the current record's "id" value
 * @method string      getEmail()     Returns the current record's "email" value
 * @method boolean     getSubscribe() Returns the current record's "subscribe" value
 * @method Newsletters setId()        Sets the current record's "id" value
 * @method Newsletters setEmail()     Sets the current record's "email" value
 * @method Newsletters setSubscribe() Sets the current record's "subscribe" value
 * 
 * @package    realstate
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsletters extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('newsletters');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('email', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('subscribe', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}