<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $name_ar
 * @property string $category_icon
 * @property string $category_icon_ar
 * @property enum $status
 * @property boolean $featured
 * @property Doctrine_Collection $State
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getNameAr()           Returns the current record's "name_ar" value
 * @method string              getCategoryIcon()     Returns the current record's "category_icon" value
 * @method string              getCategoryIconAr()   Returns the current record's "category_icon_ar" value
 * @method enum                getStatus()           Returns the current record's "status" value
 * @method boolean             getFeatured()         Returns the current record's "featured" value
 * @method Doctrine_Collection getState()            Returns the current record's "State" collection
 * @method Category            setId()               Sets the current record's "id" value
 * @method Category            setName()             Sets the current record's "name" value
 * @method Category            setNameAr()           Sets the current record's "name_ar" value
 * @method Category            setCategoryIcon()     Sets the current record's "category_icon" value
 * @method Category            setCategoryIconAr()   Sets the current record's "category_icon_ar" value
 * @method Category            setStatus()           Sets the current record's "status" value
 * @method Category            setFeatured()         Sets the current record's "featured" value
 * @method Category            setState()            Sets the current record's "State" collection
 * 
 * @package    realstate
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name_ar', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('category_icon', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('category_icon_ar', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('status', 'enum', 8, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'active',
              1 => 'inactive',
             ),
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('featured', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('State', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}