<?php

/**
 * BaseStateSlug
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $state_id
 * @property string $slug
 * @property boolean $main
 * @property boolean $disabled
 * @property State $State
 * 
 * @method integer   getId()       Returns the current record's "id" value
 * @method integer   getStateId()  Returns the current record's "state_id" value
 * @method string    getSlug()     Returns the current record's "slug" value
 * @method boolean   getMain()     Returns the current record's "main" value
 * @method boolean   getDisabled() Returns the current record's "disabled" value
 * @method State     getState()    Returns the current record's "State" value
 * @method StateSlug setId()       Sets the current record's "id" value
 * @method StateSlug setStateId()  Sets the current record's "state_id" value
 * @method StateSlug setSlug()     Sets the current record's "slug" value
 * @method StateSlug setMain()     Sets the current record's "main" value
 * @method StateSlug setDisabled() Sets the current record's "disabled" value
 * @method StateSlug setState()    Sets the current record's "State" value
 * 
 * @package    realstate
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStateSlug extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('state_slug');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('state_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('main', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('disabled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));


        $this->index('slug_index', array(
             'fields' => 
             array(
              0 => 'id',
              1 => 'slug',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('State', array(
             'local' => 'state_id',
             'foreign' => 'id'));
    }
}