<?php

/**
 * BaseCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $name_ar
 * @property boolean $active
 * @property Doctrine_Collection $City
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method string              getNameAr()  Returns the current record's "name_ar" value
 * @method boolean             getActive()  Returns the current record's "active" value
 * @method Doctrine_Collection getCity()    Returns the current record's "City" collection
 * @method Country             setId()      Sets the current record's "id" value
 * @method Country             setName()    Sets the current record's "name" value
 * @method Country             setNameAr()  Sets the current record's "name_ar" value
 * @method Country             setActive()  Sets the current record's "active" value
 * @method Country             setCity()    Sets the current record's "City" collection
 * 
 * @package    realstate
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('country');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name_ar', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('City', array(
             'local' => 'id',
             'foreign' => 'country_id'));
    }
}