<?php

/**
 * NewslettersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewslettersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewslettersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Newsletters');
    }
}