<?php

/**
 * StateSlugTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StateSlugTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StateSlugTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StateSlug');
    }
}