<?php

/**
 * sfGuardUserEmailTokensTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserEmailTokensTable extends PluginsfGuardUserEmailTokensTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserEmailTokensTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserEmailTokens');
    }
}