<?php

/**
 * BasesfGuardUserEmailTokens
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sf_guard_user_id
 * @property string $email_address
 * @property string $email_token
 * @property timestamp $token_expire_date
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer                getSfGuardUserId()     Returns the current record's "sf_guard_user_id" value
 * @method string                 getEmailAddress()      Returns the current record's "email_address" value
 * @method string                 getEmailToken()        Returns the current record's "email_token" value
 * @method timestamp              getTokenExpireDate()   Returns the current record's "token_expire_date" value
 * @method sfGuardUser            getSfGuardUser()       Returns the current record's "sfGuardUser" value
 * @method sfGuardUserEmailTokens setSfGuardUserId()     Sets the current record's "sf_guard_user_id" value
 * @method sfGuardUserEmailTokens setEmailAddress()      Sets the current record's "email_address" value
 * @method sfGuardUserEmailTokens setEmailToken()        Sets the current record's "email_token" value
 * @method sfGuardUserEmailTokens setTokenExpireDate()   Sets the current record's "token_expire_date" value
 * @method sfGuardUserEmailTokens setSfGuardUser()       Sets the current record's "sfGuardUser" value
 * 
 * @package    realstate
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserEmailTokens extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_email_tokens');
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('email_address', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('email_token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('token_expire_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}