<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sf_guard_user_id
 * @property string $first_name
 * @property string $last_name
 * @property string $username
 * @property boolean $email_verified
 * @property string $mobile
 * @property boolean $mobile_verified
 * @property string $address
 * @property date $birth_date
 * @property enum $gender
 * @property integer $total_points
 * @property string $referral_code
 * @property text $checkins
 * @property text $interests
 * @property timestamp $last_login
 * @property string $last_ip
 * @property string $profile_picture
 * @property integer $percentage_complete
 * @property string $fb_id
 * @property string $fb_name
 * @property text $fb_serialize
 * @property string $twitter_id
 * @property string $twitter_name
 * @property text $social_accounts
 * @property string $source
 * @property text $uses_mobile
 * @property boolean $newsletter
 * @property text $user_settings
 * @property integer $district_id
 * @property integer $city_id
 * @property integer $country_id
 * @property integer $refered_by
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer            getSfGuardUserId()       Returns the current record's "sf_guard_user_id" value
 * @method string             getFirstName()           Returns the current record's "first_name" value
 * @method string             getLastName()            Returns the current record's "last_name" value
 * @method string             getUsername()            Returns the current record's "username" value
 * @method boolean            getEmailVerified()       Returns the current record's "email_verified" value
 * @method string             getMobile()              Returns the current record's "mobile" value
 * @method boolean            getMobileVerified()      Returns the current record's "mobile_verified" value
 * @method string             getAddress()             Returns the current record's "address" value
 * @method date               getBirthDate()           Returns the current record's "birth_date" value
 * @method enum               getGender()              Returns the current record's "gender" value
 * @method integer            getTotalPoints()         Returns the current record's "total_points" value
 * @method string             getReferralCode()        Returns the current record's "referral_code" value
 * @method text               getCheckins()            Returns the current record's "checkins" value
 * @method text               getInterests()           Returns the current record's "interests" value
 * @method timestamp          getLastLogin()           Returns the current record's "last_login" value
 * @method string             getLastIp()              Returns the current record's "last_ip" value
 * @method string             getProfilePicture()      Returns the current record's "profile_picture" value
 * @method integer            getPercentageComplete()  Returns the current record's "percentage_complete" value
 * @method string             getFbId()                Returns the current record's "fb_id" value
 * @method string             getFbName()              Returns the current record's "fb_name" value
 * @method text               getFbSerialize()         Returns the current record's "fb_serialize" value
 * @method string             getTwitterId()           Returns the current record's "twitter_id" value
 * @method string             getTwitterName()         Returns the current record's "twitter_name" value
 * @method text               getSocialAccounts()      Returns the current record's "social_accounts" value
 * @method string             getSource()              Returns the current record's "source" value
 * @method text               getUsesMobile()          Returns the current record's "uses_mobile" value
 * @method boolean            getNewsletter()          Returns the current record's "newsletter" value
 * @method text               getUserSettings()        Returns the current record's "user_settings" value
 * @method integer            getDistrictId()          Returns the current record's "district_id" value
 * @method integer            getCityId()              Returns the current record's "city_id" value
 * @method integer            getCountryId()           Returns the current record's "country_id" value
 * @method integer            getReferedBy()           Returns the current record's "refered_by" value
 * @method sfGuardUser        getSfGuardUser()         Returns the current record's "sfGuardUser" value
 * @method sfGuardUserProfile setSfGuardUserId()       Sets the current record's "sf_guard_user_id" value
 * @method sfGuardUserProfile setFirstName()           Sets the current record's "first_name" value
 * @method sfGuardUserProfile setLastName()            Sets the current record's "last_name" value
 * @method sfGuardUserProfile setUsername()            Sets the current record's "username" value
 * @method sfGuardUserProfile setEmailVerified()       Sets the current record's "email_verified" value
 * @method sfGuardUserProfile setMobile()              Sets the current record's "mobile" value
 * @method sfGuardUserProfile setMobileVerified()      Sets the current record's "mobile_verified" value
 * @method sfGuardUserProfile setAddress()             Sets the current record's "address" value
 * @method sfGuardUserProfile setBirthDate()           Sets the current record's "birth_date" value
 * @method sfGuardUserProfile setGender()              Sets the current record's "gender" value
 * @method sfGuardUserProfile setTotalPoints()         Sets the current record's "total_points" value
 * @method sfGuardUserProfile setReferralCode()        Sets the current record's "referral_code" value
 * @method sfGuardUserProfile setCheckins()            Sets the current record's "checkins" value
 * @method sfGuardUserProfile setInterests()           Sets the current record's "interests" value
 * @method sfGuardUserProfile setLastLogin()           Sets the current record's "last_login" value
 * @method sfGuardUserProfile setLastIp()              Sets the current record's "last_ip" value
 * @method sfGuardUserProfile setProfilePicture()      Sets the current record's "profile_picture" value
 * @method sfGuardUserProfile setPercentageComplete()  Sets the current record's "percentage_complete" value
 * @method sfGuardUserProfile setFbId()                Sets the current record's "fb_id" value
 * @method sfGuardUserProfile setFbName()              Sets the current record's "fb_name" value
 * @method sfGuardUserProfile setFbSerialize()         Sets the current record's "fb_serialize" value
 * @method sfGuardUserProfile setTwitterId()           Sets the current record's "twitter_id" value
 * @method sfGuardUserProfile setTwitterName()         Sets the current record's "twitter_name" value
 * @method sfGuardUserProfile setSocialAccounts()      Sets the current record's "social_accounts" value
 * @method sfGuardUserProfile setSource()              Sets the current record's "source" value
 * @method sfGuardUserProfile setUsesMobile()          Sets the current record's "uses_mobile" value
 * @method sfGuardUserProfile setNewsletter()          Sets the current record's "newsletter" value
 * @method sfGuardUserProfile setUserSettings()        Sets the current record's "user_settings" value
 * @method sfGuardUserProfile setDistrictId()          Sets the current record's "district_id" value
 * @method sfGuardUserProfile setCityId()              Sets the current record's "city_id" value
 * @method sfGuardUserProfile setCountryId()           Sets the current record's "country_id" value
 * @method sfGuardUserProfile setReferedBy()           Sets the current record's "refered_by" value
 * @method sfGuardUserProfile setSfGuardUser()         Sets the current record's "sfGuardUser" value
 * 
 * @package    realstate
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('sf_guard_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email_verified', 'boolean', null, array(
             'type' => 'boolean',
             'default' => '0',
             'notnull' => true,
             ));
        $this->hasColumn('mobile', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('mobile_verified', 'boolean', null, array(
             'type' => 'boolean',
             'default' => '0',
             'notnull' => true,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('birth_date', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('gender', 'enum', 6, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'male',
              1 => 'female',
             ),
             'length' => 6,
             ));
        $this->hasColumn('total_points', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('referral_code', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('checkins', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('interests', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('last_ip', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('profile_picture', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('percentage_complete', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fb_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fb_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fb_serialize', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('twitter_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('twitter_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('social_accounts', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('source', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('uses_mobile', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('newsletter', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('user_settings', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('district_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('city_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('country_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('refered_by', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}