<?php

/**
 * PluginsfGuardUserEmailTokensTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardUserEmailTokensTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardUserEmailTokensTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardUserEmailTokens');
    }
}